# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Release

env:
    VITE_FIRESTORE_API_KEY: ${{ secrets.VITE_FIRESTORE_API_KEY }}
    VITE_FIRESTORE_APP_ID: ${{ secrets.VITE_FIRESTORE_APP_ID }}
    VITE_FIRESTORE_AUTH_DOMAIN: ${{ secrets.VITE_FIRESTORE_AUTH_DOMAIN }}
    VITE_FIRESTORE_DATABASE_URL: ${{ secrets.VITE_FIRESTORE_DATABASE_URL }}
    VITE_FIRESTORE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIRESTORE_MESSAGING_SENDER_ID }}
    VITE_FIRESTORE_PROJECT_ID: ${{ secrets.VITE_FIRESTORE_PROJECT_ID }}
    VITE_FIRESTORE_STORAGE_BUCKET: ${{ secrets.VITE_FIRESTORE_STORAGE_BUCKET }}

on:
    push:
        tags:
            - "*" # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 22.x
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: "npm"
            - run: npm ci
            - run: npm run lint
            - run: npm run build
            - name: Archive build
              uses: actions/upload-artifact@v4
              with:
                  name: release
                  path: ./dist
                  retention-days: 1
    ftp-deploy:
        name: ðŸŽ‰ Publish release
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: ðŸšš Checkout
              uses: actions/checkout@v4
            - name: Download a single artifact
              uses: actions/download-artifact@v4
              with:
                  name: release
                  path: dist
            - name: ðŸ“‚ Sync files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.6
              with:
                  server: ${{ secrets.ftpServer }}
                  username: ${{ secrets.ftpUsername }}
                  password: ${{ secrets.ftpPassword }}
                  protocol: ftps
                  port: ${{ secrets.ftpPort }}
                  local-dir: dist
                  server-dir: /www/thalos-companion-web/
                  dry-run: true
                  dangerous-clean-slate: true
